### ISSUE TITLE
Contributing instructions?

### ISSUE THREAD

**Issue by marccampbell** [gettaylor/taylor#14]
We'd like to run an instance of taylor in Slack, but due to compliance and security issues, we'd like to deploy a self-hosted version of the bot. Are there setup instructions to allow someone to run a private instance of Taylor?

I think we'd need to create our own Slack app, but I'm not sure what scopes we'd need and what environment variables to export.

**Comment by lcampbe79** [comment]
Hi @marccampbell, you can check out the scopes and other requirements here (6ae39d6) on the CONTRIBUTING.md. There are also screenshots to help as well.
